Correct mechanism to sigalg mapping for RSA-SHA384/512
google/native-pkcs11 pull request #306
Opened 2024-06-03 16:59 UTC by sake

The mapping from the Mechanism to SignatureAlgorithm contains a twisted value. The result is that RsaPkcsSha384 gets mapped to RsaPkcs1v15Sha512 and vice versa.

2024-06-03 22:41 UTC, brandonweeks requested changes
Thank you for catching this and sending a PR! Please see the message from @google-cla.

2024-06-04 09:22 UTC, sake commented
> Thank you for catching this and sending a PR! Please see the message from @google-cla.

Thanks for the swift reply! However I don't understand what you expect me to do. I didn't get any message in my emails (junk checked), the google CLA page, or over github notifications.

2024-06-04 16:35 UTC, brandonweeks approved these changes

2024-06-04 16:36 UTC, brandonweeks commented
Apologies! I failed to notice the CLA GitHub action was green.

2024-06-05 06:50 UTC, merged